usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

tienda:
    resource: "@TiendaBundle/Controller/"
    type:     annotation
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Controller/"
    type:     annotation
    prefix:   /ciudad

oferta:
    resource: "@OfertaBundle/Controller/"
    type:     annotation
    prefix:   /oferta

pagina_ayuda:
   pattern: /ayuda
   defaults: { _controller: OfertaBundle:Default:ayuda }
   
pagina_estatica:
   pattern: /sitio/{pagina}
   defaults:  { _controller: OfertaBundle:Sitio:estatica}
_pagina_estatica:
   pattern: /sitio/{pagina}/
   defaults: { _controller: OfertaBundle:Sitio:estatica }
   
#ruta para la portada principal#
portada:
   pattern: /portada
   defaults: { _controller: OfertaBundle:Default:portada }
