backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

tienda:
    resource: "@TiendaBundle/Controller/"
    type:     annotation
    prefix:   /tienda

ciudad:
    resource: "@CiudadBundle/Controller/"
    type:     annotation
    prefix:   /ciudad

oferta:
    pattern: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

pagina_ayuda:
   pattern: /ayuda
   defaults: { _controller: OfertaBundle:Default:ayuda }
   
pagina_estatica:
   pattern: /sitio/{pagina}
   defaults:  { _controller: OfertaBundle:Sitio:estatica}
_pagina_estatica:
   pattern: /sitio/{pagina}/
   defaults: { _controller: OfertaBundle:Sitio:estatica }

#ruta para la portada principal#
portada:
   pattern: /{ciudad}                                     #aca debajo establecemos la ciudad por defecto#
   defaults: { _controller: OfertaBundle:Default:portada, ciudad:'%cupon.ciudad_por_defecto%' }
   