security:

   firewalls: 
      frontend:
         pattern:     ^/
         anonymous:   ~
         form_login:  
            login_path: /usuario/login
            check_path: /usuario/login_check
            default_target_path: /

         logout:
            path: usuario_logout
            target: /
         

   access_control:
       - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/usuario/*, roles: ROLE_USUARIO }
      
      
   providers:
      usuarios:
         entity: { class: cupon\UsuarioBundle\Entity\Usuario, property: email }
      
       
   encoders:
      cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
      
         
         