<?php

namespace cupon\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository
{
	
	public function findOfertaDelDia($ciudad)
	{
		$fechaPublicacion = new \DateTime('today');
		$fechaPublicacion->setTime(23, 59, 59);
		$em = $this->getEntityManager();
		$dql = 'SELECT o FROM OfertaBundle:Oferta o WHERE o.ciudad = :ciudad';
		
		$consulta = $em->createQuery($dql);
		$consulta->setParameter('ciudad', $ciudad);
		return $consulta->getSingleResult();
	}
}
