<?php

namespace cupon\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository
{
	
	public function findOfertaDelDia($ciudad)
	{
		$em = $this->getEntityManager();
		$consulta = $em->createQuery('
            SELECT o
            FROM OfertaBundle:Oferta o Join o.ciudad c
			WHERE c.slug = :ciudad
        ');
		
		$consulta->setParameter('ciudad', $ciudad);
		$consulta->setMaxResults(1);
		return $consulta->getOneOrNullResult();
	}
}
