usuario_compras:
   pattern: /compras
   defaults: { _controller: UsuarioBundle:Default:compras }

usuario_login:
   pattern: /login
   defaults: { _controller: UsuarioBundle:Default:login }

usuario_login_check:
   pattern: /login_check
   #aca no va nada porque lo hace automaticamente symfony

usuario_logout:
   pattern: /logout
   #aca no va nada porque lo hace automaticamente symfony