services:
   login_listener:
      class: cupon\UsuarioBundle\Listener\LoginListener
      arguments: [@router]
      tags:
         - { name: kernel.event_listener, event: security.interactive_login }#suscription al evento interactive_login
         - { name: kernel.event_listener, event: kernel.response }#suscripcion al evento response