<?php

namespace cupon\TiendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TiendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiendaRepository extends EntityRepository
{
}
